<?php
/*- init helper -*/
$helper = Mage::helper('chartmap');
$bg_color 		= $helper->cmap_bgcolor();
$border_color 	= $helper->cmap_bordercolor();
$color 			= $helper->cmap_color();
?>
<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head">
				<?php echo $this->__('World Map');?>
				</h3>
			</td>
            <td class="form-buttons">&nbsp;</td>
        </tr>
    </tbody></table>
</div>
<div class="panel panel-default">
	<!--
	<div class="panel-heading">
		<h3 class="panel-title"><i class="fa fa-eye"></i> <?php echo "World Map"; ?></h3>
	</div> -->
	<div class="panel-body">
		<div id="vmap" style="width: 100%; height: 400px;border: 1px solid activeborder;"></div>
	</div>
</div>

<script type="text/javascript">
jQuery(document).ready(function() {
	data = [];
	var json = '<?php echo $this->getTotalOrdersByCountry(); ?>';
	json = JSON.parse(json);
	for (i in json) {
		data[i] = json[i]['total'];
	}
	jQuery('#vmap').vectorMap({
		map: 'world_en',
		backgroundColor: '<?php echo $bg_color; ?>',
		borderColor: '<?php echo $border_color; ?>',
		color: '<?php echo $color; ?>',
		hoverOpacity: 0.7,
		selectedColor: '#666666',
		enableZoom: true,
		showTooltip: true,
		values: data,
		normalizeFunction: 'polynomial',
		onLabelShow: function(event, label, code) {
			if (json != null && json[code]) {
			/* if (json[code]) { */
				label.html('<strong>' + label.text() + '</strong><br />' + '<?php echo "Order(s) "; ?> ' + json[code]['total'] + '<br />' + '<?php echo "Sale(s) "; ?> ' + json[code]['amount']);
			}
		}
	});	
});
</script> 
