<?php
/*- init helper -*/
$helper = Mage::helper('chartmap');
?>
<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head">
				<?php echo $this->__('Customer Group Report');?>
				</h3>
			</td>
            <td class="form-buttons">&nbsp;</td>
        </tr>
    </tbody></table>
</div>
<div class="panel panel-default">
	<div class="panel-body">
		

<?php
$results = $this->getTotalOrdersByCustomerGroupName();
if(count($results) > 0 ) {
	$chartData = "['Order', 'Customer Group'],";
	foreach ($results as $result) {
		$group_name = ucwords($result['customer_group_name']);
		$count  = $result['total'];
		$chartData .=  "['". $group_name ."', ". $count."], ";
	}
	$chartData = substr($chartData, 0, -2);
?>
		<!-- <script type="text/javascript" src="https://www.google.com/jsapi"></script>-->
		<script type="text/javascript">
		google.load("visualization", "1", {packages:["corechart"]});
		google.setOnLoadCallback(drawChart);
		
		function drawChart() {

		var data = google.visualization.arrayToDataTable([ <?php echo $chartData; ?>]);

		var options = { title: 'Sale(s) By Customer Group', is3D: true, pieHole: 0.4,};
		
		var chart = new google.visualization.PieChart(document.getElementById('piechart'));

		chart.draw(data, options);
		}
		</script>
		<div id="piechart" style="width: 100%; height: 500px;border: 1px solid activeborder;"></div>
	
<?php } else {	?>
		<div id="" style="width: 900px; height: 500px;">No Data Found for Bulid Pie Chart</div>
<?php }	?>
	</div>
</div>